### ISSUE TITLE
Need performance improvement on ReactiveSeq.combinations(size)

### ISSUE THREAD

**Issue by landawn** [aol/cyclops-react#526] opened 2017-03-24 22:16 UTC
There are only a few results but It take long time to run: 

`ReactiveSeq.range(1, 32).combinations(32);`
`ReactiveSeq.range(1, 32).combinations(31);`

**Comment by johnmcclean-aol** [comment] 2017-03-27 10:56
The current implementation uses Streamable which is likely to be the cause of the slowness. It should be possible to implement this via forEach2 (now that ReactiveSeq instances are themselves replayable in 2.x - see this thread https://github.com/aol/cyclops-react/issues/512).

We should test it to confirm it speeds things up significantly, but I suspect it will make a big difference.

**Comment by landawn** [comment] 2017-03-27 17:03
Here is one of the faster implementation:

`
    @Test
    public void test_combinations() {
        final int size = 4;
        String[] a = { "a", "b", "c", "e", "f", "g" };
        final int fromIndex = 0;
        final int toIndex = a.length;
    
        final Iterator<List<String>> iter = new Iterator<List<String>>() {
            private final int[] indices = Array.range(fromIndex, fromIndex + size);
    
            @Override
            public boolean hasNext() {
                return indices[0] <= toIndex - size;
            }
    
            @Override
            public List<String> next() {
                final List<String> result = new ArrayList<>(size);
    
                for (int idx : indices) {
                    result.add(a[idx]);
                }
    
                if (++indices[size - 1] == toIndex) {
                    for (int i = size - 1; i > 0; i--) {
                        if (indices[i] > toIndex - (size - i)) {
                            indices[i - 1]++;
    
                            for (int j = i; j < size; j++) {
                                indices[j] = indices[j - 1] + 1;
                            }
                        }
                    }
                }
    
                return result;
            }
        };
    
        iter.forEachRemaining(System.out::println);
    }
`

**Comment by johnmcclean-aol** [comment] 2017-03-28 10:23
Ideally combinations for ReactiveSeq should perform at a level roughly equivalent to this. Because it's a Stream we'll have to use nested flatMap operations rather than for loops (which is what forEach2 expands out to).

**Comment by landawn** [comment] 2017-03-28 14:58
why have to use flatMap? this implementation is iteration, not the general for loops.

**Comment by johnmcclean-aol** [comment] 2017-03-28 16:32
Ah..

So, I'm not sure how, but I completely missed that there was an Iterator defined there :)

ReactiveSeq can work both iteratively (pull based) and like an Rx-style Observable (push based), there is a Spliterator and Observable style Operator already for flatMap - which means a solution defined in terms of flatMap would work coherently in both pull and push modes. 

Otherwise we could define both a Spliterator (will typically perform better than a raw Iterator) for the iterative mode and a push based Operator. Separate implementations may drive better performance, but involve more maintenance overhead.

I think if a flatMap approach came reasonably close to your implementation in performance it would be easier to maintain long term - if not then creating separate Spliterators and Operators instances would be worth it.

**Comment by landawn** [comment] 2017-03-28 16:59
John, The method is almost not usable by current implementation when the size reach certain number. The implementation I post here is many times faster. You could more do investigation if you're willing to.

**Comment by johnmcclean-aol** [comment] 2017-03-29 12:03
It looks like it is, thanks!

One way to implement it is to use forEach2 (for comprehension with a sliding window) the code could look something like this 

```java 
   @Override
    public ReactiveSeq<ReactiveSeq<T>> combinations(final int size) {
        return forEach2(a->
                        this.drop(1).sliding(size-1),
                        (a,b)-> b.prepend(a).reactiveSeq());

    }
```

That approach is over 3X faster that the current implementation, but unfortunately is still around 10X slower than your approach above. (JMH results).

I think that makes a pretty strong case for adopting your approach. ReactiveSeq instance could be created directly from an Iterator of via the Java 9 style iterate creation operator. I think the only changes required are to lazily convert each nested List to ReactiveSeq and to capture the output of the original Stream (to populate a local array).

Benchmark                                                               Mode     Cnt   Score    Error  Units
**reactiveSeq.Combinations.iteratorCombos                               sample  260523   0.001 ±  0.001  ms/op**
reactiveSeq.Combinations.iteratorCombos:iteratorCombos·p0.00          sample          ≈ 10⁻³           ms/op
reactiveSeq.Combinations.iteratorCombos:iteratorCombos·p0.50          sample           0.001           ms/op
reactiveSeq.Combinations.iteratorCombos:iteratorCombos·p0.90          sample           0.001           ms/op
reactiveSeq.Combinations.iteratorCombos:iteratorCombos·p0.95          sample           0.001           ms/op
reactiveSeq.Combinations.iteratorCombos:iteratorCombos·p0.99          sample           0.003           ms/op
reactiveSeq.Combinations.iteratorCombos:iteratorCombos·p0.999         sample           0.017           ms/op
reactiveSeq.Combinations.iteratorCombos:iteratorCombos·p0.9999        sample           0.066           ms/op
reactiveSeq.Combinations.iteratorCombos:iteratorCombos·p1.00          sample           1.763           ms/op
**reactiveSeq.Combinations.reactiveSeqCombos                            sample  187410   0.007 ±  0.001  ms/op**
reactiveSeq.Combinations.reactiveSeqCombos:reactiveSeqCombos·p0.00    sample           0.005           ms/op
reactiveSeq.Combinations.reactiveSeqCombos:reactiveSeqCombos·p0.50    sample           0.005           ms/op
reactiveSeq.Combinations.reactiveSeqCombos:reactiveSeqCombos·p0.90    sample           0.010           ms/op
reactiveSeq.Combinations.reactiveSeqCombos:reactiveSeqCombos·p0.95    sample           0.013           ms/op
reactiveSeq.Combinations.reactiveSeqCombos:reactiveSeqCombos·p0.99    sample           0.029           ms/op
reactiveSeq.Combinations.reactiveSeqCombos:reactiveSeqCombos·p0.999   sample           0.081           ms/op
reactiveSeq.Combinations.reactiveSeqCombos:reactiveSeqCombos·p0.9999  sample           0.909           ms/op
reactiveSeq.Combinations.reactiveSeqCombos:reactiveSeqCombos·p1.00    sample           2.638           ms/op
**reactiveSeq.Combinations.streamableCombos                             sample  211558   0.024 ±  0.001  ms/op**
reactiveSeq.Combinations.streamableCombos:streamableCombos·p0.00      sample           0.017           ms/op
reactiveSeq.Combinations.streamableCombos:streamableCombos·p0.50      sample           0.019           ms/op
reactiveSeq.Combinations.streamableCombos:streamableCombos·p0.90      sample           0.034           ms/op
reactiveSeq.Combinations.streamableCombos:streamableCombos·p0.95      sample           0.041           ms/op
reactiveSeq.Combinations.streamableCombos:streamableCombos·p0.99      sample           0.074           ms/op
reactiveSeq.Combinations.streamableCombos:streamableCombos·p0.999     sample           0.153           ms/op
reactiveSeq.Combinations.streamableCombos:streamableCombos·p0.9999    sample           1.068           ms/op
reactiveSeq.Combinations.streamableCombos:streamableCombos·p1.00      sample          12.845           ms/op

**Comment by johnmcclean-aol** [comment] 2017-04-25 13:33
Merged on master

**Closed by johnmcclean-aol** 2017-04-25 13:33 UTC
Labels: enhancement
